# Meta Arguments: What job? What train .py file? Base config? Where to store?
meta_job_args:
    project_name: "es_bench"
    experiment_type: "hyperparameter-search"
    base_train_fname: "train.py"
    base_train_config: "configs/OpenES/ant.yaml"
    experiment_dir: "experiments/OpenES/ant"

# Parameters specific to the hyperparameter search
param_search_args:
    search_logging:
        max_objective: True
        aggregate_seeds: "mean"
        problem_type: "best"
        eval_metrics:
            - "test_perf"
    search_resources:
        num_search_batches: 1
        num_evals_per_batch: 36
        num_seeds_per_eval: 1
    search_config:
        search_type: "Grid"
        search_schedule: "sync"
        search_params:
          categorical:
            es_params/sigma_init: [0.01, 0.025, 0.05, 0.075, 0.1, 0.125]
            opt_params/lrate_init: [0.005, 0.0075, 0.01, 0.02, 0.03, 0.04]

# Parameters specific to an individual job
single_job_args:
    job_name: "es_bench"
    num_gpus: 1
    num_logical_cores: 4
    log_file: "log"
    err_file: "err"
    # env_name: "jax-cuda"
    env_name: "snippets"
    time_per_job: "00:06:00"
    # partition:
    #     - "ex_scioi_gpu"
    # #     - "scioi_gpu"
    # gpu_type: "v100s"
    # memory_per_cpu: 10000
    gpu_prefix: "cuda"
    queue:
        - "cognition-all.q"
    # exclude_nodes:
    #   - "cognition14.ml.tu-berlin.de"