train_config:
  num_generations: 200
  evaluate_every_gen: 10
  num_devices: 4
  device_type: "cpu"

  es_name: "OpenES"
  es_config:
    popsize: 100
    opt_name: "adam"
  es_params:
    lrate_init: 0.01
    lrate_decay: 0.999
    lrate_limit: 0.001
    sigma_init: 0.03
    sigma_decay: 0.999
    sigma_limit: 0.01

  problem_name: "Gym"
  problem_train_config:
    env_name: "CartPole-v1"
    num_env_steps: 200
    num_rollouts: 20
  problem_test_config:
    env_name: "CartPole-v1"
    num_env_steps: 200
    num_rollouts: 164
  
  fitness_config:
    maximize: true
    centered_rank: true
    z_score: true
    w_decay: 0.0

  network_name: "LSTM"
  network_config: 
    num_hidden_units: 16
    output_activation: "categorical"

log_config:
  time_to_track: ["num_gens", "num_total_steps"]
  what_to_track: ["train_perf_best", "train_perf_gen_mean",
                  "test_perf_best", "test_perf_strat_mean"]
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"