train_config:
  num_generations: 2000
  eval_every_gen: 10
  strategy_name: "OpenES"
  popsize: 128
  task_config:
    env_name: "Pong-v5"
    max_steps: 500
    num_envs_per_member: 2
  model_config:
    hidden_dims: [32]
  es_params:
    sigma_init: 0.01
    init_min: 0.0
    init_max: 0.0
  es_config:
    lrate_init: 0.003
    maximize: true
    centered_rank: true

log_config:
  time_to_track: ["num_gens"]
  what_to_track: 
    - "mean_pop_perf"
    - "max_pop_perf"
    - "best_pop_perf"
    - "test_eval_perf"
    - "best_eval_perf"
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: evobench
    group: atari
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1