train_config:
  env_name: "mnist"
  num_generations: 4000
  eval_every_gen: 50
  strategy_name: "CMA_ES"
  popsize: 128
  normalize_obs: False
  es_config:
    elite_ratio: 0.5
    maximize: true
  es_params:
    sigma_init: 0.025
    init_min: 0.0
    init_max: 0.0
  eval_config:
    n_repeats: 1
    test_n_repeats: 1
    n_evaluations: 1


log_config:
  time_to_track: ["num_gens"]
  what_to_track: ["train_perf", "test_perf"]
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"

device_config:
  device_type: "gpu"
  num_devices: 1