train_config:
  env_name: "fetch"
  num_generations: 2000
  eval_every_gen: 50
  strategy_name: "Sep_CMA_ES"
  popsize: 256
  normalize_obs: True
  model_config:
    hidden_layers: 4
    hidden_dims: 32
  task_config:
    max_steps: 1000
  es_config:
    centered_rank: True
    maximize: true
    elite_ratio: 0.2
  es_params:
    sigma_init: 0.125
    init_min: 0.0
    init_max: 0.0
  eval_config:
    n_repeats: 16
    test_n_repeats: 1
    n_evaluations: 128


log_config:
  time_to_track: ["num_gens"]
  what_to_track: ["train_perf", "test_perf"]
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: false
  wandb_config:
    project: es-bench
    group: Sep_CMA_ES-fetch
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1