train_config:
  env_name: "SpaceInvaders-MinAtar"
  num_generations: 4000
  eval_every_gen: 50
  strategy_name: "OpenES"
  popsize: 256
  normalize_obs: False
  es_config:
    centered_rank: True
    maximize: true
    lrate_init: 0.01
    lrate_decay: 0.999
    lrate_limit: 0.001
  es_params:
    sigma_init: 0.05
    sigma_decay: 0.999
    sigma_limit: 0.01
    init_min: 0.0
    init_max: 0.0
  eval_config:
    n_repeats: 4
    test_n_repeats: 1
    n_evaluations: 64


log_config:
  time_to_track: ["num_gens"]
  what_to_track: ["train_perf", "test_perf"]
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: es-bench
    group: cma-spaceinvarders
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1