train_config:
  num_generations: 2000
  evaluate_every_gen: 40
  num_devices: 1
  device_type: "gpu"

  es_name: "PGPE"
  es_config:
    popsize: 100
    opt_name: "adam"
  es_params:
    lrate_init: 0.01
    lrate_decay: 0.999
    lrate_limit: 0.001
    sigma_init: 0.03
    sigma_decay: 0.999
    sigma_limit: 0.01
    init_min: 0.0
    init_max: 0.0

  problem_name: "Vision"
  problem_train_config:
    task_name: "MNIST"
    batch_size: 1024
  problem_test_config:
    task_name: "MNIST"
    batch_size: 10000

  fitness_config:
    maximize: true
    centered_rank: false
    z_score: false
    w_decay: 0.0

  network_name: "CNN"
  network_config: 
    depth_1: 1
    depth_2: 1
    features_1: 8
    features_2: 16
    kernel_1: 5
    kernel_2: 5
    strides_1: 1
    strides_2: 1
    num_linear_layers: 0

log_config:
  time_to_track: ["num_gens", "num_total_steps"]
  what_to_track: ["train_perf_best", "train_perf_gen_mean",
                  "test_perf_best", "test_perf_strat_mean"]
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"