wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1669494483
    t:
      1:
      - 1
      - 5
      - 6
      - 12
      - 45
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 12
      - 45
      - 53
      - 55
      3:
      - 16
      4: 3.9.7
      5: 0.12.17
      8:
      - 5
device_config:
  desc: null
  value:
    device_type: gpu
    num_devices: 1
log_config:
  desc: null
  value:
    model_type: jax
    overwrite: 1
    print_every_k_updates: 1
    time_to_track:
    - num_gens
    use_wandb: true
    verbose: true
    wandb_config:
      group: cma-ant
      name: seed0
      project: es-bench
    what_to_track:
    - test_perf
train_config:
  desc: null
  value:
    es_config:
      elite_ratio: 0.5
      maximize: true
    es_params:
      init_max: 0.5
      init_min: 0.5
      sigma_init: 0.15
    num_generations: 100
    popsize: 8
    strategy_name: Sep_CMA_ES
