train_config:
  env_name: "mnist"
  num_generations: 4000
  eval_every_gen: 100
  strategy_name: "Sep_CMA_ES"
  popsize: 128
  normalize_obs: False
  model_config:
    num_hidden_layers: 0
    num_hidden_units: 0
  task_config:
    batch_size: 1024
  es_config:
    elite_ratio: 0.5
  es_params:
    sigma_init: 0.025
    init_min: 0.0
    init_max: 0.0

log_config:
  time_to_track: ["num_gens"]
  what_to_track:
    - "mean_pop_perf"
    - "max_pop_perf"
    - "best_pop_perf"
    - "test_eval_perf"
    - "best_eval_perf"
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: evo-bench
    group: mnist
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1